stages:
  load_data:
    cmd: python src/load_data_heart.py --config=heart_params.yaml
    deps:
    - src/get_data_heart.py
    - src/load_data_heart.py
    - source_data/heart.csv

    outs:
    - data/raw/heart_mlflow.csv

  split_data:
    cmd: python src/split_data_heart.py --config=heart_params.yaml
    deps:
    - src/split_data_heart.py
    - data/raw/heart_mlflow.csv

    outs:
    - data/processed/train_heart.csv
    - data/processed/test_heart.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate_heart.py --config=heart_params.yaml
    deps:
    - data/processed/train_heart.csv
    - data/processed/test_heart.csv
    - src/train_and_evaluate_heart.py

    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio

    metrics:
    - reports/heart_scores.json
      cache: false
    - reports/heart_params.json
      cache: false
    outs:
    - models/model.joblib

  #log_production_model:
  #  cmd: python src/log_production_model_heart.py --config=params.yaml
  #  deps:
  #    - src/log_production_model_heart.py


