stages:
  load_data:
    cmd: python src/mri/split_mri.py --config=mri_params.yaml
    deps:
      - src/mri/get_data_mri.py
      - src/mri/split_mri.py
      - source_data/
    outs:
      - data/processed:
          persist: true

  train_model:
    cmd: python src/mri/model_train_mri.py --config=mri_params.yaml
    deps:
      - src/mri/get_data_mri.py
      - src/mri/model_train_mri.py
    outs:
      - saved_models:
          persist: true
      - reports:
          persist: true

  evaluate:
    cmd: python src/mri/evaluate.py --config=mri_params.yaml
    deps:
      - src/mri/get_data.py
      - src/mri/evaluate.py